name: ursa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18648
title: 'ursa::things get done'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#905f4e'
    - '#e5b69a'
    - '#4d133b'
    - '#c3334c'
    - '#fbfbf7'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
