typography_spectrum: 0.5522328743245453
color:
  brandColors:
    - '#030208'
    - '#d5d6ce'
    - '#c7a889'
    - '#37342d'
    - '#817f68'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7328195001464337
analytics:
  google: null
  facebook: null
  twitter: null
name: ursa
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: shop
    url: 'https://poshmark.com/closet/woolblanket'
    type: external
favicon: null
title: ''
description: ''
purpose:
  - type: external
    url: poshmark.com/closet/woolblanket
    label: S|H|O|P
