name: ursa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18648
title: 'ursa::things get done'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030208'
    - '#d5d6ce'
    - '#c7a889'
    - '#37342d'
    - '#817f68'
  brandStrength: 0.5625
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
